spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.207:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  cloud:
    bus:
    trace:
      enabled: true
  rabbitmq:
    host: 192.168.192.131
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:
  port: 9082
